name: Release kernel deb packages
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      patch_kernel:
        description: "Patch kernel to new version"
        required: true
        default: false
        type: boolean
      kernel_version:
        description: "Select kernel version"
        required: false
        default: '92'
        type: string
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - name: Prepare
        run: |
          apt-get -y update
          apt-get -y install git lsb-release gcc-aarch64-linux-gnu bison flex libssl-dev libelf-dev debhelper bc rsync kmod cpio

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare repository
        run: git config --global --add safe.directory "$(pwd)"

      - name: Patching kernel to 6.6.$kernel_version
        if: (inputs.patch_kernel == 'true' && inputs.kernel_version == 'true')
        run: |
          for i in {61..$kernel_version}; do
            fp=$(($i-1))-$i
            wget -q "https://www.kernel.org/pub/linux/kernel/v6.x/incr/patch-6.6.$fp.xz"
            unxz patch-6.6.$fp.xz
            echo "Patching kernel 6.6.$(($i-1)) to 6.6.$i"
            patch -p1 < patch-6.6.$fp*
            rm patch-6.6.$fp
          done

      - name: SSH connection to Actions
        uses: csexton/debugger-action@master
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')

      - name: Build
        run: |
          export CROSS_COMPILE=aarch64-linux-gnu-
          export ARCH=arm64
          export LOCALVERSION=
          make LOCALVERSION= mrproper
          make uz801v3_defconfig
          make deb-pkg -j"$(($(grep -c processor < /proc/cpuinfo)*2))"

      - name: Prepare artifacts
        run: mkdir artifacts && mv ../linux-* artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: artifacts/*

  bootimg:
    name: Make boot images
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare
        run: |
          sudo apt-get -y update
          sudo apt-get -y install binfmt-support qemu-user-static mkbootimg
          mkdir artifacts

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download kernel
        uses: actions/download-artifact@v4
        with:
          name: kernel
          path: artifacts

      - name: Build
        run: |
          cd .github/scripts
          sudo ./build_boot_img.sh

      - name: Generate release info
        run: git log -1 --format=%B > changes.txt

      - name: Releases
        uses: softprops/action-gh-release@v2
        with:
          body_path: changes.txt
          files: artifacts/*
